### PR TITLE
qgis2-ltr: 2.14.14

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by dakcarto** [comment]
Hi @m-kuhn! Thanks for these version bumps.

Under the current Travis setup, please comment out the 'bottle' block as well. Otherwise, the auto-uploaded bottle's version is also bumped. Sorry, kind of manual a process right now.

**Comment by m-kuhn** [comment]
Sure.
How's this process working? Bottles are created and uploaded but not published until you manually write them back in a separate manually prepared commit?

**Comment by dakcarto** [comment]
> How's this process working? Bottles are created and uploaded but not published until you manually write them back in a separate commit?

Correct. It can be automated, using an older [brew-test-bot.rb](https://github.com/Homebrew/homebrew-test-bot), but back when it was part of the homebrew-core tap and simpler (current version won't work for Travis-only deployment, I think). Such a script can update the formula's bottle block and auto-commit the changes, as part of the Travis setup, after the S3 bucket upload. Haven't found the time to include/hack that file yet.

Another tidbit, when bumping the base formula version, e.g. 2.14.13 -> 2.14.14, any formula `revision #` should be cleared as well. No harm in leaving it in, if it is `revision 1`, like `qgis2` and `qgis2-ltr` were at.

Most syntactic nit picks, and errors, can be found by running `brew audit --strict --online <formula>` before and _after_ installing a formula change.

**Comment by m-kuhn** [comment]
> Such a script can update the formula's bottle block and auto-commit the changes, as part of the Travis setup, after the S3 bucket upload.

I always thought that the github repo itself is the repo for travis. But in this case it would be an external S3 repo (also git?)

Or commit back to the same repo (possibly using ci skip)?

**Comment by dakcarto** [comment]
> Or commit back to the same repo (possibly using ci skip)?

Yes.

This is the automated Travis workflow (not finished yet):
* Build formula and run test block
* Upon successful test, bottle binary
* Upload bottle to S3 bucket
* [*] (Re)write the new bottle block to the current formula's .rb file
* [*] Auto-commit .rb file back to this github repo, but with `[ck skip]` appended to message

[*] Not done yet, but code already exists in older Homebrew core setup.

Then, more macOS versions can be added to the Travis matrix.

Note: At Essen QGIS dev meeting, I'd like to work on getting macOS Travis working again upstream for QGIS `master` and clean up any failing tests. So, getting this automated setup finished is a also important.

**Comment by m-kuhn** [comment]
https://github.com/m-kuhn/QGIS/pull/48

Build is running already. Only the scripts need to be finetuned (because of sip warnings from  qscintilla) and plenty of tests fixed. And then possibly autobottling introduced ;)

**Pull request merged**
