### PR TITLE
Re #1022 add support PROJ4 v 6.0

### PR DESCRIPTION
**Pull request by winsento**
Fix https://github.com/OSGeo/homebrew-osgeo4mac/issues/1022 Define `CUSTOM_DEFINES=-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H`

Check after install:
1. `mapnik-config --proj-lib` must show path to PROJ_LIB directory
2. `mapnik-config --defines` with defined `-DMAPNIK_USE_PROJ4`

### CODE REVIEW

**Comment by fjperini** [comment]
@winsento it looks like he is using PROJ6:

```
Checking for PROJ_LIB directory...pj_open_lib returned /usr/local/Cellar/osgeo-proj/6.0.0_3/share/proj/ 
```

The error in `high_sierra-build` is due to:

```
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of gdal library... yes
Checking for C++ library gdal... no
Checking for C library pq... yes
Checking if gdal is ogr enabled... yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of ogr library... yes
Checking for C++ library gdal... no
Checking for cairo freetype font support ... yes

Exiting... the following required dependencies were not found:
   - boost regex (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)

See '/private/tmp/osgeo-mapnik-20190409-9279-xtpmzr/mapnik-v3.0.22/config.log' for details on possible problems.

Also, these OPTIONAL dependencies were not found:
   - boost program_options (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)
   - boost_regex_icu (libboost_regex built with optional ICU unicode support is needed for unicode regex support in mapnik.)
   - gdal (GDAL C++ library | configured using gdal-config program | try setting GDAL_CONFIG SCons option | more info: https://github.com/mapnik/mapnik/wiki/GDAL)
```

let's check `sierra-build`, then we solve the above.

**Comment by winsento** [comment]
@fjperini hm it's looks like boost library was built without regex+icu support.

**Comment by fjperini** [comment]
I've seen in sierra builds well

```
==> ./configure CC=/usr/bin/clang CXX=/usr/bin/clang++ -std=c++11 -stdlib=libc++ PREFIX=/usr/local/Cellar/osgeo-mapnik/3.0.22_1 CPP_TESTS=FALSE INPUT_PLUGINS=all NIK2IMG=FALSE CUSTOM_DEFINES=-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H JOBS=2 CUSTOM_CXXFLAGS=-I/usr/local/opt/sqlite/include CUSTOM_LDFLAGS=-L/usr/local/opt/sqlite/lib -lsqlite3 LINKING=shared RUNTIME_LINK=shared THREADING=multi INTERNAL_LIBAGG=False BENCHMARK=FALSE BOOST_INCLUDES=/usr/local/opt/boost/include BOOST_LIBS=/usr/local/opt/boost/lib FREETYPE_CONFIG=/usr/local/opt/freetype/bin/freetype-config FREETYPE_INCLUDES=/usr/local/opt/freetype/include/freetype2 FREETYPE_LIBS=/usr/local/opt/freetype/lib CAIRO=TRUE CAIRO_INCLUDES=/usr/local/opt/cairo/include CAIRO_LIBS=/usr/local/opt/cairo/lib PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/X11/lib/pkgconfig GRID_RENDERER=TRUE SVG_RENDERER=TRUE PNG=TRUE PNG_INCLUDES=/usr/local/opt/libpng/include PNG_LIBS=/usr/local/opt/libpng/lib JPEG=TRUE JPEG_INCLUDES=/usr/local/opt/jpeg/include JPEG_LIBS=/usr/local/opt/jpeg/lib TIFF=TRUE TIFF_INCLUDES=/usr/local/opt/libtiff/include TIFF_LIBS=/usr/local/opt/libtiff/lib WEBP=TRUE WEBP_INCLUDES=/usr/local/opt/webp/include WEBP_LIBS=/usr/local/opt/webp/lib GEOS_CONFIG=/usr/local/opt/geos/bin/geos-config GDAL_CONFIG=/usr/local/opt/osgeo-gdal/bin/gdal-config OCCI_INCLUDES=/usr/local/opt/osgeo-gdal/include OCCI_LIBS=/usr/local/opt/osgeo-gdal/lib RASTERLITE_INCLUDES=/usr/local/opt/osgeo-gdal/bin RASTERLITE_LIBS=/usr/local/opt/osgeo-gdal/bin XML2_CONFIG=/usr/local/opt/libxml2/bin/xml2-config XML2_INCLUDES=/usr/local/opt/libxml2/include XML2_LIBS=/usr/local/opt/libxml2/lib HB_INCLUDES=/usr/local/opt/harfbuzz/include HB_LIBS=/usr/local/opt/harfbuzz/lib PROJ=TRUE PROJ_INCLUDES=/usr/local/opt/osgeo-proj/include PROJ_LIBS=/usr/local/opt/osgeo-proj/lib PG_CONFIG=/usr/local/opt/osgeo-postgresql/bin/pg_config PG_INCLUDES=/usr/local/opt/osgeo-postgresql/include PG_LIBS=/usr/local/opt/osgeo-postgresql/lib PGSQL2SQLITE=True
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
Configuring on Darwin in *release mode*...
Checking for dlfcn.h support ... yes
Checking if compiler (/usr/bin/clang++ -std=c++11 -stdlib=libc++) supports -std=c++11 flag... (cached) yes
Checking for C library freetype... yes
Checking for C library z... yes
Checking for C++ library icuuc... yes
Checking for ICU version >= 4.2... found: icu 63.1
(cached) Checking for C++ library harfbuzz... yes
Checking for HarfBuzz version >= 0.9.34... found: HarfBuzz 2.4.0
Checking for HarfBuzz with freetype support
(cached) yes
Searching for boost libs and headers... (cached) 
Found boost libs: /usr/local/opt/boost/lib
Found boost headers: /usr/local/opt/boost/include
Checking for C++ header file boost/version.hpp... yes
Checking for Boost version >= 1.47... yes
Found boost lib version... 1_69
Checking for C++ library boost_system... yes
.
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_regex... yes
Checking for C++ library boost_program_options... yes
Checking whether Boost was compiled with C++11 scoped enums ... yes
Checking if boost_regex was built with ICU unicode support... (cached) no
Checking for C library jpeg... yes
Checking for C library proj... yes
Checking for C library png... yes
Checking for C library webp... yes
Checking for C library tiff... yes
Checking for PROJ_LIB directory...pj_open_lib returned /usr/local/Cellar/osgeo-proj/6.0.0_3/share/proj/ 
Checking for ICU data directory...icu-config returned /usr/local/Cellar/icu4c/63.1/share/icu/63.1
Checking for GDAL data directory...GDAL_PREFIX returned /usr/local/Cellar/osgeo-gdal/2.4.1_2/share/gdal

Checking for pkg-config... yes
Checking for requested plugins dependencies...
Checking for C library pq... yes
Checking for C library sqlite3... yes
Checking if SQLite supports RTREE... (cached) yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of gdal library... yes
Checking for C++ library gdal... yes
Checking for C library pq... yes
Checking if gdal is ogr enabled... yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of ogr library... yes
Checking for C++ library gdal... yes
Checking for cairo freetype font support ... yes

All Required dependencies found!

Saving new file 'config.py'...
Will hold custom path variables from commandline and python config file(s)...

Note: will build without these OPTIONAL dependencies:
   - boost_regex_icu (libboost_regex built with optional ICU unicode support is needed for unicode regex support in mapnik.)

Configure completed: run `make` to build or `make install`
==> make
# we first build memory intensive files with -j1
python scons/scons.py -j1 \
		--config=cache --implicit-cache --max-drift=1 \
		src/renderer_common/render_group_symbolizer.os \
		src/renderer_common/render_markers_symbolizer.os \
		src/renderer_common/render_thunk_extractor.os \
		src/json/libmapnik-json.a \
		src/wkt/libmapnik-wkt.a \
		src/css_color_grammar.os \
		src/expression_grammar.os \
		src/transform_expression_grammar.os \
		src/image_filter_grammar.os \
		src/marker_helpers.os \
		src/svg/svg_transform_parser.os \
		src/agg/process_line_symbolizer.os \
		plugins/input/geojson/geojson_datasource.os \
		utils/mapnik-index/process_geojson_file.o \
		src/svg/svg_path_parser.os \
		src/svg/svg_parser.os \
		src/svg/svg_points_parser.os \
		src/svg/svg_transform_parser.os \

scons: Reading SConscript files ...
Using previous successful configuration...
Re-configure by running "python scons/scons.py configure".

Welcome to Mapnik...

scons: done reading SConscript files.
scons: Building targets ...
```

`sierra-build`: https://circleci.com/api/v1.1/project/github/OSGeo/homebrew-osgeo4mac/4290/output/107/0?file=true

**Comment by fjperini** [comment]
I have applied some changes, let's check if it is due to that.

**Comment by winsento** [comment]
@fjperini I can not reproduce the problem, can we somehow see log?
`/private/tmp/osgeo-mapnik-20190409-9279-xtpmzr/mapnik-v3.0.22/config.log`

It looks like Scons does not find `libboost_regex` in path `/usr/local/opt/boost/lib`. Need to see if it is there.

**Comment by fjperini** [comment]
I could upload `config.log` to artifacts.
One possible solution is ` brew link boost --force` to make sure.

**Comment by fjperini** [comment]
@winsento the problem is in `high sierra`, the same thing happens in `homebrew-core`.

https://github.com/Homebrew/homebrew-core/blob/893d2b0451b482af8ed944e04577d6e8a590f8f8/Formula/mapnik.rb#L8-L12

Maybe it's related to https://github.com/Homebrew/homebrew-core/pull/33077 

We will use  Sierra bottle for High Sierra and Mojave. 

In Mojave build well!.

**Comment by winsento** [comment]
@fjperini ok, I can analyze it tonight.

**Comment by fjperini** [comment]
@winsento ok!
It seems to work well in Mojave.

```
$ mapnik-config --proj-lib
/usr/local/Cellar/osgeo-proj/6.0.0_3/share/proj/

$ mapnik-config --defines
-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DDARWIN -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DSVG_RENDERER
```

**Comment by winsento** [comment]
@fjperini maybe apply this PR and create new issue for problem with boost on High Sierra? Because this is different problems.

**Comment by fjperini** [comment]
@winsento will you open an issue in this tap or in the mapnik repo?

**Comment by winsento** [comment]
@fjperini i can't report issue about `boost regex` because can't reproduce and research it on High Sierra. On my mac Mojave installed.

**Comment by fjperini** [comment]
@winsento it will be used proj5 for a time #1177.
The problem in HS is external to this tap.

**Pull request closed without merging**
