### PR TITLE
Formula for qgis 2.10.1

### PR DESCRIPTION
**Pull request by christianurich**
the formal is based on the qgis-28.rb. The only things changed are the references to qgis 2.10 and I uncommented the patch.

### CODE REVIEW

**Comment by pjduplooy** [comment]
Hi christianurich

Thanx for this!! Actually was planning to do something similar over our long weekend this weekend, but you saved me the trouble!!

**Comment by christianurich** [comment]
Maybe you can pull it and see if it works for you. I have not properly tested all the dependencies, e.g. grass,... so I can't tell if it works in all cases. But for a basic installation it seems to work fine.

**Comment by pjduplooy** [comment]
Wlll do that, Thanx!  I know on linux and windows theres still a problem with grass 7 and processing

**Comment by davenquinn** [comment]
I pulled this into my local branch and tried to install — I ended up with a build failure at the following point:

    [ 66%] Linking CXX executable ../../output/bin/QGIS.app/Contents/MacOS/QGIS
    cd /tmp/qgis-21020150816-46135-cwc3ra/QGIS-final-2_10_1/build/src/app &&     /usr/local/Cellar/cmake/3.3.1/bin/cmake -E cmake_link_script CMakeFiles/QGIS.dir/link.txt  ... [truncated for brevity]
    [ 66%] Built target QGIS
    make: *** [all] Error 2

**Comment by christianurich** [comment]
can you try to build it with --verbose and post the log file

**Comment by davenquinn** [comment]
Here are the logfiles from a verbose build:

https://drive.google.com/folderview?id=0BzFTyjxorIWAfjg1amRwcFIwWkdJR3NqV3pibHRzTjlndU9MQk10eEhma0YxUlEyN3ljVE0&usp=sharing

**Comment by christianurich** [comment]
Thanks, that is a problem with grass. If you don't need it you can try --without-grass
I'll have a look at it later this week and try to fix the compile error.

**Comment by nlebedev** [comment]
I'm trying to build with this formula, and get a make error.
```brew install --with-api-docs --with-grass7 --with-r -v qgis-210``` fails with
```[ 51%] Built target postgresprovider
make: *** [all] Error 2```

Full logs are here:
https://gist.github.com/a9b3c6cd6556ac26ab7e

**Comment by christianurich** [comment]
Hi all I added @dakcarto 's patch to fix the compile problems with grass.  Let me know if it fixes the compile problems

**Comment by nlebedev** [comment]
@christianurich I can't build ```--with-globe``` option set. However, qgis-210 gets built ok without it. 
When this option is set I get:
```
[ 95%] Built target QGIS
make: *** [all] Error 2
```

My build logs:
https://gist.github.com/7d9bf32799da88c6eb70

osgEarth itself works normally as expected. Can anyone confirm qgis-210 gets built ```--with-globe```?

**Comment by davenquinn** [comment]
I believe that `--with-globe` was broken in the previous version as well? Or, at least, the plugin itself didn't work regardless of whether it built.

**Comment by mofoyoda** [comment]
@christianurich did you try bumping version to 2.12? I'm using your 2.10 formula, but want to make sure it works with 2.12 before messing around. QGIS is usually quite hard to build.

**Comment by christianurich** [comment]
I gave it a try but run into a compile error. Didn't have time yet to look into details.

**Comment by dakcarto** [comment]
Thank you for your contribution and effort debugging.

Closing in favor of 2.14 formula in #123

**Pull request closed without merging**
