### PR TITLE
update osgeo-qt-webkit to 5.14

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by frankli0324** [comment]
Error: Your Xcode (8.3.3) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or
https://developer.apple.com/download/more/.

image

**Comment by 3nids** [comment]
@frankli0324 this has been fixed here https://github.com/OSGeo/homebrew-osgeo4mac/commit/2f8b1d9c1bc7933a79e16dc1d044456bdb1326e9

trying once more

**Comment by 3nids** [comment]
@fjperini is it good for you now that sierra has been dropped?

**Comment by fjperini** [comment]
@3nids I already fixed the saw compilation and made some adjustments to have the bottles for Catalina

**Comment by 3nids** [comment]
@fjperini thanks, but how does it work? are you doing this on your machine or is this happening bon circle-ci?

**Comment by fjperini** [comment]
@3nids In CI. But the new version of QT no longer compiles in the saw, so I will copy the HG bottle for Sierra in this case.

**Pull request closed without merging**
