### PR TITLE
qt5-webkit: fixed

### PR DESCRIPTION
**Pull request by fjperini**
Solution for the problem reported in #481 #476 #471

@nickrobison First you must merge #483 to generate through the bottle.

### CODE REVIEW

**Comment by nickrobison** [comment]
@fjperini Can you give me some more details into what changes you made in order resolve the issues?

But thanks for digging into this!

**Comment by fjperini** [comment]
@nickrobison Yes, wait, I will apply some minor changes.

**Comment by fjperini** [comment]
@nickrobison this does not happen anymore:

```
# just let it install to qt5 formula prefix
# NOTE: this violates sandboxing, so --no-sandbox during install required
```

I've fixed the permissions problems by setting `CMAKE_INSTALL_PREFIX` in `/Tools/qmake/projects/run_cmake.pro`.

All files are installed correctly in `/usr/local/Cellar/qt5-webkit/5.11.2` and it is no longer necessary to move them.
```
mv Dir["#{qt5.opt_lib}/QtWebKit*.framework"], "#{lib}/"
mv Dir["#{qt5.opt_lib}/cmake/Qt5WebKit*"], "#{lib}/cmake/"
mv Dir["#{qt5.opt_lib}/pkgconfig/Qt5WebKit*.pc"], "#{lib}/pkgconfig/"
mv Dir["#{qt5.opt_prefix}/mkspecs/modules/qt_lib_webkit*.pri"], "#{prefix}/mkspecs/modules/"
#mv qt5.opt_prefix/"plugins/webkit", "#{prefix}/plugins/"
mv qt5.opt_prefix/"qml/QtWebKit", "#{prefix}/qml/"
mv qt5.opt_libexec/"QtWebProcess", "#{libexec}/"
```

I will apply some minor changes.

p/d: the build time is within the limits of Travis, so the bottle can be created.

**Comment by fjperini** [comment]
@nickrobison I already made the corrections, everything works perfectly.

**Pull request merged**
