### PR TITLE
QGIS 2.18.18

### PR DESCRIPTION
**Pull request by luisspuerto**
Now I think this is the last version

### CODE REVIEW

**Comment by 3nids** [comment]
If I understand correctly gdal2 is built on an older libproj.
Triggering a new build of gdal2 in #343 to see if it improves the situation

**Comment by nickrobison** [comment]
@3nids Can you rerun this build? I just successfully built on my local machine.

Nice work @luisspuerto!

**Comment by 3nids** [comment]
yep.
strange, Travis seems to have pushed the bottle
image

but in another build
image

**Comment by luisspuerto** [comment]
What can I do? Do I just make a empty commit?

**Comment by nickrobison** [comment]
@3nids The issue is that the bottles are being uploaded with a revision attached, but the formula is still pointing to the old bottle version. Not sure why, it looks like the CI script isn't updating the formula with the bottle information. Were these being built manually before?

@luisspuerto Nothing you can go right now, your formula is working great! It built successfully on my machine as well, we'll just have to get the bottling working again, and then your script will build correctly.

**Comment by 3nids** [comment]
@nickrobison not sure how it works
https://github.com/OSGeo/homebrew-osgeo4mac/commit/73c972b23401f29fee097b5988053722f8ff28f8 
I see no sign of automatic update of the bottles in the travis code and nothing in the above commit let me think otherwise.

**Comment by 3nids** [comment]
issue seems to be in before_deploy
image

**Comment by 3nids** [comment]
I suspect this issue comes from the copy line in before_deploy.
But I wonder if this is the right approach to copy the same bottle for high sierra. Shall we just do bottles for high sierra and drop sierra, or create matrix build?

**Comment by nickrobison** [comment]
@3nids I opened #346 to discuss the bottle issue and try to come up with a plan going forward.

**Comment by kbevers** [comment]
Can this be merged now that #346 has been resolved?

**Comment by luisspuerto** [comment]
@kbevers Yeah I think so... I guess that @3nids or @nickrobison will merge it when they have a moment. Today is Sunday and perhaps they aren't in front of a computer.

**Comment by kbevers** [comment]
> I guess that @3nids or @nickrobison will merge it when they have a moment. Today is Sunday and perhaps they aren't in front of a computer.

Of course, no rush. I was just genuinely curious if this was finished since I just tried installing the existing qgis2 formula. Unfortunately it has a few issues making it a bit of a hassle. I hope that is fixed with this updated formula.

**Comment by nickrobison** [comment]
@kbevers @luisspuerto Sorry for the delay in getting this merged.

We've run into a couple of issues on the CI system, which we've been battling for the last couple of days. Specifically, #328.

We're hoping to get all the GDAL formulae updating with new bottles, and then merge in the remaining formula changes that depend on them. I'll have some time today to keep working on the CI system, so hopefully we can merge either today or tomorrow.

**Comment by kbevers** [comment]
@nickrobison don't worry. You guys are doing a fantastic job. It is no trouble at all to wait a bit longer!

**Comment by nickrobison** [comment]
@kbevers @3nids @luisspuerto Merged!

Thanks for your patience and thanks to @luisspuerto for getting this updated!

**Pull request merged**
