### PR TITLE
Add qgis3 and fix-matplotlib+python

### PR DESCRIPTION
**Pull request by fjperini**
This new pull is for to have a version of https://github.com/OSGeo/homebrew-osgeo4mac/pull/403 cleaned.

I detail the few changes I made as I found errors in the previous pull.

before_install.sh: add tap `brewsci/bio` for `matplotlib`

.travis.yml: fix for python version. Requires `python3`

`sudo ln -sf /usr/local/bin/python3 /usr/local/bin/python` 

Temporary, only on travis. We have to add a fix for this in the formula.

The same for `pyrcc5`

`sudo cp ./scripts/pyrcc5.sh /usr/local/bin/pyrcc5`

And I added the scripts that were in the origin folder (qgis/qgis3-dev)

### CODE REVIEW

**Comment by fjperini** [comment]
According to the registry, `qt5-webkit` is installed. But something happens that the dependency is not found when starting the installation of `qgis3`.

```
==> Installing qgis3 from osgeo/osgeo4mac
qt5-webkit: Must be built with `brew install --no-sandbox ...`, or install steps will fail.
Error: An unsatisfied requirement failed this build.
Testing changed formula qgis3...
Error: Testing requires the latest version of osgeo/osgeo4mac/qgis3
```

In the previous pull, I corrected this temporarily by installing `qt5-webkit` from `.travis.yml`

**Comment by fjperini** [comment]
Clear! :pray: I wait for you to finish.
This time, I only made some Commits. :sweat_smile:

**Comment by nickrobison** [comment]
Please rebase this against the latest set of commits, which should remove the need to build qgis3 with the `--no-sandbox` flag.

**Comment by fjperini** [comment]
A problem with the formula after rebase. Conflict with the file.

```
syntax error, unexpected <<, expecting keyword_end
<<<<<<< HEAD
```
The best thing will be to make a new pull.

**Pull request closed without merging**
