### PR TITLE
Upgrade PGSQL-OGR-FDW to 1.0.7

### PR DESCRIPTION
**Pull request by fjperini**
It was changed to `postgis2`/`gdal2` and fixed build.

### CODE REVIEW

**Comment by fjperini** [comment]
@nickrobison It will be necessary to rebuild the bottles. (see https://github.com/OSGeo/homebrew-osgeo4mac/pull/531#issuecomment-440907711)

```
==> Installing osgeo/osgeo4mac/pgsql-ogr-fdw dependency: postgis2
==> Downloading https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/postgis2-2.5
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "postgis2"
Download failed: https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/postgis2-2.5.1.sierra.bottle.tar.gz
```

**Comment by nickrobison** [comment]
@fjperini The postgis2 bottle is not building, Travis can’t seem to find the formula, did you verify that it passed brew audit?

**Comment by fjperini** [comment]
@nickrobison `brew audit` only suggests minor changes

This informs for the [previous pull](https://travis-ci.com/OSGeo/homebrew-osgeo4mac/builds/92219431):

```
$ if [ "${CHANGED_FORMULAE}" == "" ]; then echo "Skipping CI; no changed formulae found in $TRAVIS_BUILD_DIR"; travis_terminate 0; else echo "Changed formulae are ${CHANGED_FORMULAE}"; fi
Skipping CI; no changed formulae found in /Users/travis/build/OSGeo/homebrew-osgeo4mac
```

It seems that now if you are building: see #536

**Comment by fjperini** [comment]
@nickrobison Problems when performing the test:

```
==> Summary
🍺  /usr/local/Cellar/pgsql-ogr-fdw/1.0.7: 26 files, 294.4KB, built in 7 seconds
Testing changed formula pgsql-ogr-fdw...
Testing osgeo/osgeo4mac/pgsql-ogr-fdw
==> ogr_fdw_info -s /usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data -l pt_two
Error: osgeo/osgeo4mac/pgsql-ogr-fdw: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <"CREATE SERVER myserver\n  FOREIGN DATA WRAPPER ogr_fdw\n  OPTIONS (\n    datasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',\n    format 'ESRI Shapefile' );\n\nCREATE FOREIGN TABLE pt_two (\n  fid integer,\n  geom geometry,\n  name varchar,\n  age integer,\n  height real,\n  birthdate date )\n  SERVER myserver\n  OPTIONS ( layer 'pt_two' );"> expected but was
<"CREATE SERVER myserver\n  FOREIGN DATA WRAPPER ogr_fdw\n  OPTIONS (\n\tdatasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',\n\tformat 'ESRI Shapefile' );\n\nCREATE FOREIGN TABLE pt_two (\n  fid bigint,\n  geom Geometry(Point,4326),\n  name varchar,\n  age integer,\n  height real,\n  birthdate date\n) SERVER myserver\nOPTIONS (layer 'pt_two');">.
diff:
  CREATE SERVER myserver
    FOREIGN DATA WRAPPER ogr_fdw
    OPTIONS (
-     datasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',
? ^^^^
+ 	datasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',
? ^
-     format 'ESRI Shapefile' );
? ^^^^
+ 	format 'ESRI Shapefile' );
? ^
  
  CREATE FOREIGN TABLE pt_two (
-   fid integer,
-   geom geometry,
+   fid bigint,
+   geom Geometry(Point,4326),
    name varchar,
    age integer,
    height real,
-   birthdate date )
?                 --
+   birthdate date
-   SERVER myserver
? ^
+ ) SERVER myserver
? ^
-   OPTIONS ( layer 'pt_two' );
? --         -              -
+ OPTIONS (layer 'pt_two');
```

**Comment by fjperini** [comment]
@nickrobison for some reason, he insists on applying those changes:

```
diff:
  CREATE SERVER myserver
    FOREIGN DATA WRAPPER ogr_fdw
    OPTIONS (
-         datasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',
? ^^^^^^^^
+ 	datasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',
? ^
-         format 'ESRI Shapefile' );
? ^^^^^^^^
+ 	format 'ESRI Shapefile' );
? ^
```
The test will be simplified using only:

```
ogr_fdw_info -s /usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data
```

**Comment by nickrobison** [comment]
@fjperini The issue is that the posts test is expecting a tab character `\t` before the _datasource_ and _format_ lines. If you actually inspect the two text strings, you can see the difference.

```
<"CREATE SERVER myserver\n  FOREIGN DATA WRAPPER ogr_fdw\n  OPTIONS (\n  \tdatasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',\n  \tformat 'ESRI Shapefile' );\n\nCREATE FOREIGN TABLE pt_two (\n  fid bigint,\n  geom Geometry(Point,4326),\n  name varchar,\n  age integer,\n  height real,\n  birthdate date\n) SERVER myserver\nOPTIONS (layer 'pt_two');"> expected but was
<"CREATE SERVER myserver\n  FOREIGN DATA WRAPPER ogr_fdw\n  OPTIONS (\n\tdatasource '/usr/local/Cellar/pgsql-ogr-fdw/1.0.7/data',\n\tformat 'ESRI Shapefile' );\n\nCREATE FOREIGN TABLE pt_two (\n  fid bigint,\n  geom Geometry(Point,4326),\n  name varchar,\n  age integer,\n  height real,\n  birthdate date\n) SERVER myserver\nOPTIONS (layer 'pt_two');">.
```
I was able to get the test to pass by the following stepsL:

1. Insert a tab character before the text in lines 67 and 68.
2. Add a new line right after the first `EOS` and right before the second EOS.
3. Change the `strip` commands to `gsub(' ','')`. (To remove any extra whitespacing)

I know it's not a great idea to rely on parsing text output for tests, but I want to make sure that we're actually verify that the correct changes are being applied in exactly the way we're expecting.

Thanks for your work on this, hopefully we can get it merged in soon.

**Comment by fjperini** [comment]
@nickrobison If you can try to correct the problem of insert a tab character, I do it from my editor but it seems not to recognize it.

**Pull request merged**
