### PR TITLE
Bump qt5-webkit to 5.9.0

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
@dakcarto any idea what's going wrong here?

```
Error: inreplace failed
/usr/local/Cellar/qt5-webkit/5.9.0_1/mkspecs/modules/qt_lib_webkit.pri:
  expected replacement of "$$QT_MODULE_LIBEXEC_BASE" with "/usr/local/opt/qt5-webkit/libexec"
  expected replacement of "$$QT_MODULE_PLUGIN_BASE" with "/usr/local/opt/qt5-webkit/plugins/webkit"
  expected replacement of "$$QT_MODULE_QML_BASE" with "/usr/local/opt/qt5-webkit/qml"
```

https://travis-ci.org/OSGeo/homebrew-osgeo4mac/builds/242297775#L1485-L1487

**Comment by timlinux** [comment]
Any news on this @dakcarto ? It would be great to be able to build with WebKit again!

**Comment by m-kuhn** [comment]
@timlinux did you ever try to build this in the end? I remember we were interrupted when working on it.

**Comment by dakcarto** [comment]
@m-kuhn, @timlinux I'm working on this formula right now. Try to build 5.9.1 in 10.1.6 under Xcode 8.3.3.

**Comment by dakcarto** [comment]
@m-kuhn @timlinux, `qt5-webkit` [updated to 5.9.1](https://github.com/OSGeo/homebrew-osgeo4mac/commits/master/Formula/qt5-webkit.rb) and Sierra bottle added. No issues on 10.12.6, while I see a crash on 10.11.6 related to `libqcorewlanbearer` plugin (though it works with `libgenericbearer`):

```
Crashed Thread:        10  Qt bearer thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_NSXPCDistantObjectWithError startMonitoringEventWithType:reply:]: unrecognized selector sent to instance 0x7fc7b35856b0'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff8a44b452 __exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff828a2f7e objc_exception_throw + 48
2   CoreFoundation                      0x00007fff8a4b518d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x00007fff8a3bb4c1 ___forwarding___ + 1009
4   CoreFoundation                      0x00007fff8a3bb048 _CF_forwarding_prep_0 + 120
5   CoreWLAN                            0x00007fff919d56a3 -[CWWiFiClient __startMonitoringEventWithType:reply:] + 228
6   CoreWLAN                            0x00007fff919d59d8 -[CWWiFiClient startMonitoringEventWithType:error:] + 189
7   libqcorewlanbearer.dylib            0x000000011593bfb8 qt_plugin_instance + 6792
8   libqcorewlanbearer.dylib            0x000000011594083c qt_plugin_instance + 25356
9   QtCore                              0x000000010d8dbd51 _ZN7QObject5eventEP6QEvent + 801
10  QtCore                              0x000000010d8b22bf _ZN23QCoreApplicationPrivate13notify_helperEP7QObjectP6QEvent + 303
11  QtCore                              0x000000010d8b1eb9 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 185
12  QtCore                              0x000000010d8b2ffb _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData + 891
13  QtCore                              0x000000010d908209 _ZN20QEventDispatcherUNIX13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 73
14  QtCore                              0x000000010d8ada31 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 417
15  QtCore                              0x000000010d6e4ed3 _ZN7QThread4execEv + 115
16  QtCore                              0x000000010d6e8c3f _ZN18QThreadStorageData6finishEPPv + 2463
17  libsystem_pthread.dylib             0x00007fff82d3299d _pthread_body + 131
18  libsystem_pthread.dylib             0x00007fff82d3291a _pthread_body + 0
19  libsystem_pthread.dylib             0x00007fff82d30351 thread_start + 13

```

**Comment by timlinux** [comment]
I still have a wierd thing that since upgrading to Qt 5.9 etc. and enabling webkit I don't get Processing, DB Manager and other tools that rely on webkit built.

**Comment by dakcarto** [comment]
@timlinux, looks like the Python bindings are maybe not included, or the internal ones are not being built.

**Comment by timlinux** [comment]
@dakcarto can you share your CMakeCache.txt so I can see what I am missing?

**Comment by dakcarto** [comment]
@timlinux, I've added a `pyqt5-webkit` formula. Please test whether this works in real world plugin usage. Thanks!

Note, the `qt5-webkit` formula is having a small issue with its `NoQt5WebKitSandboxRequirement`, whereby you may run into this failure:
https://travis-ci.org/OSGeo/homebrew-osgeo4mac/builds/273185612

Installing `qt5-webkit` separately _first_ should avoid that for now.

**Comment by dakcarto** [comment]
Hi @timlinux, were you able to test the `pyqt5-webkit` bindings?

**Comment by timlinux** [comment]
Hi @dakcarto 

I tried uninstalling both qt5-webkit and pyqt5-webkit. And then brew updating and then installing them in the sequence of first qt5-webkit then pyqt5-webkit. Still no joy in getting processing and dbmanager and probably other bits that need pywebkit. Other python related stuff still works.

screen shot 2017-09-16 at 11 03 53 pm

**Comment by timlinux** [comment]
@dakcarto Sorry to take so long to reply - I can say that everything is working fine for me with qt5 and high Sierra with qt5-webkit for me.

**Comment by dakcarto** [comment]
@timlinux wrote:
> @dakcarto Sorry to take so long to reply - I can say that everything is working fine for me with qt5 and high Sierra with qt5-webkit for me.

Hmm. A bit odd, since the botle for `qt5-webkit` is the same (I just duplicated the Sierra bottle). :smiley: The High Sierra `qt` (Qt5) bottle is new, of course. Maybe there was a relevant change there.

**Pull request closed without merging**
