### PR TITLE
Update webkit to the latest version

### PR DESCRIPTION
**Pull request by nickrobison**
First step at addressing the webkit issues described in #403

### CODE REVIEW

**Comment by fjperini** [comment]
It's good that you're working to solve it :smiley:

**Comment by fjperini** [comment]
Look! @nickrobison 

`Error: /usr/local/opt/qt5-webkit/qml/QtWebKit/libqmlwebkitplugin.dylib: no such file`

I tried the changes. The extension is not changed, it is commented.

```
# Rename the .so files
mv "#{prefix}/qml/QtWebKit/libqmlwebkitplugin.so", "#{prefix}/qml/QtWebKit/libqmlwebkitplugin.dylib"
mv "#{prefix}/qml/QtWebKit/experimental/libqmlwebkitexperimentalplugin.so", "#{prefix}/qml/QtWebKit/experimental/libqmlwebkitexperimentalplugin.dylib"
```

**Comment by nickrobison** [comment]
I had the wrong prefix in the MachO calls, that should be fix now. If you hold on a bit, I should be able to push a bottle build with the new formula, that should save you some build time.

I don't think we'll be able to build on Travis due to the 2 hour build time required, but we should be able to keep it manually up to date.

**Comment by fjperini** [comment]
Sure, it's a long time.
I agree, it's a good solution.

**Comment by fjperini** [comment]
In case you can stop the build, and win a little time. It comes out with error:

```
==> Finishing up
Error: Not a directory @ realpath_rec - /usr/local/Cellar/qt5-webkit/5.11.1/lib/QtWebKit.framework/Versions/5/QtWebKit/Versions
```

**Pull request merged**
