### PR TITLE
Cleanup brew audit errors for assorted formulae.

### PR DESCRIPTION
**Pull request by nickrobison**

### CODE REVIEW

**Comment by 3nids** [comment]
@nickrobison just forced push after rebase on origin/master

**Comment by nickrobison** [comment]
@3nids Sounds good. Frustrating this is proving to be so difficult, but thanks for your work!

**Comment by 3nids** [comment]
some permission issues
from the (formula)[https://github.com/nickrobison/homebrew-osgeo4mac/blob/dfc00c5f450fda0625b8e5396c99a9cfabdd1982/Formula/pgsql-ogr-fdw.rb#L22-L26]
```
    # This includes PGXS makefiles and so will install __everything__
    # into the Postgres keg instead of the this formula's keg.
    # Right now, no items installed to Postgres keg need to be installed to `prefix`.
    # In the future, if `make install` installs things that should be in `prefix`
    # consult postgis formula to see how to split it up.
```

**Comment by 3nids** [comment]
merging as is to move forward

**Pull request merged**
