### PR TITLE
Add SIP-QT5 formula

### PR DESCRIPTION
**Pull request by fjperini**

### CODE REVIEW

**Comment by 3nids** [comment]
This sounds like a strange naming to me. Sip is not strictly associated to Qt. Can you explain the need of a new formula (sorry if it was said somewhere else) and the reasoning for the naming?
Cheers

**Comment by fjperini** [comment]
@3nids For several reasons:
- `sip` of `homebrew-core` is very outdated
- there were several bug reports with the associated modules
- the paths are established correctly: .`./share/sip/PyQt5 `and `../share/sip/PyQt5/Qsci`.

As for the name of the formula, the ideal is to be called equal, but it is the simplest way to apply these changes.

p/d: and there was already one in the repository with the name `sip-qt4`.

**Comment by 3nids** [comment]
Have you tried to create a PR to update the formula on core? It would the preferred approach.
I am not a huge fan of the name, but I don't mind if we have no other choice than adding this formula.

**Comment by fjperini** [comment]
I was looking at that possibility, there were several attempts at updating.
That's why I improved the formulas so that it is well built and we can use them.

I will try to upload them to homebre-core, if they combine these changes it would be great.

**Comment by 3nids** [comment]
would be perfect for homebrew...and 🤞 for you laptop!

**Comment by fjperini** [comment]
I hope that they respond satisfactorily  :crossed_fingers:, meanwhile using a virtual machine to answer simple questions.

**Pull request merged**
