### PR TITLE
fix depends on warning and <<-EOS.undent error

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by 3nids** [comment]
Remaining error:

in Formula/gpkgtools.rb line 9
`depends_on 'PIL' => :python`

screen shot 2018-01-25 at 11 50 15

**Comment by fitnr** [comment]
I turned to `brew audit`, which informs me that the line in question should be "vendored":
````
$ brew audit ./Formula/gpkgtools.rb
gpkgtools:
  * C: 9: col 24: python modules should be vendored rather than use deprecated depends_on 'PIL' => :python`
  * C: 37: col 3: Use new-style test definitions (test do)
  * Head-only (no stable download)
  * HEAD: Use of the bzr:// scheme is deprecated, pass `:using => :bzr` instead
Error: 4 problems in 1 formula
````

Based on what I've scraped together, "vendoring" would look something like this. Can't confirm because I'm getting a error on the bzr step, of all things.
```ruby
require 'formula'

class Gpkgtools < Formula
  homepage 'https://launchpad.net/gpkgtools'
  head 'http://bazaar.launchpad.net/~bradh/gpkgtools/trunk', :using => :bzr

  depends_on 'libspatialite'
  depends_on "python"

  resource "Pillow" do
    url "https://files.pythonhosted.org/packages/0f/57/25be1a4c2d487942c3ed360f6eee7f41c5b9196a09ca71c54d1a33c968d9/Pillow-5.0.0.tar.gz"
    sha256 "12f29d6c23424f704c66b5b68c02fe0b571504459605cfe36ab8158359b0e1bb"
  end

  def install
    head_ext = "#{HOMEBREW_PREFIX}/Cellar/libspatialite/HEAD/lib/spatialite.dylib"
    unless File.exist? head_ext
      odie <<~EOS
        No libspatialite HEAD build or SQLite3 extension 'spatialite.dylib' exists.
        Install libspatialite using --HEAD and --with-geopackage options'.
        NOTE: To experiment with the HEAD build, but already have libspatialite
              installed, do the following:
                `brew upgrade libspatialite --HEAD --with-geopackage`
                `brew list --versions libspatialite` (note non-HEAD version)
                `brew switch libspatialite <non-HEAD version>`
      EOS
    end

    resource("Pillow").stage { system "python", *Language::Python.setup_install_args(libexec/"vendor") }

    cd 'gpkgtools' do
      inreplace %w[util_sqlite.py GeoPackage.py] do |s|
        s.sub! 'from pysqlite2', '#from pysqlite2'
        s.sub! '#import sqlite3', 'import sqlite3'
        s.sub! /load_extension\(.*spatialite"\)/, "load_extension('#{head_ext}')"
      end
    end

    (lib/python.xy/'site-packages').install 'gpkgtools'
    bin.install Dir['*gpkg*']
    prefix.install %w[tests testdata]
  end

  def test
    cd "#{opt_prefix}" do
      system 'python', 'tests/geonames.py'
    end
  end
end
```

**Comment by nickrobison** [comment]
@3nids Can we rebase this PR on the latest changes to master? Seems like there are a lot of outstanding issues and PRs related to the deprecation warnings, it would be nice to get them resolved. Maybe the vendoring issue can be done in a later change set, since it involves more than just a semantic change?

**Comment by 3nids** [comment]
OK, I just rebased

image

**Comment by nickrobison** [comment]
@3nids I just opened #339 to hopefully address the python issues raised in the Travis build.

**Comment by 3nids** [comment]
@nickrobinson a bit better, but back to 

image

**Comment by nickrobison** [comment]
@3nids Is it possible to get this PR merged? I'm getting the following error when trying to update my homebrew install:

```
Error: Calling 'depends_on :python' is disabled!
Use 'depends_on "python@2"' instead.
/usr/local/Homebrew/Library/Taps/osgeo/homebrew-osgeo4mac/Formula/pyqt-qt4.rb:14:in `<class:PyqtQt4>'
```

Seems to imply the days of deprecation are limited.

Is there anything I can do to help out?

**Comment by kbevers** [comment]
> @nickrobison do you think we can merge with the issues in pdal?

It's better to remove the pdal formula altogether. It seems to be a very old formula (version 0.9) and [pdal has been added to homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdal.rb) some time ago. So I'd say disregard whatever problems is in the pdal formula for now and remove it in a separate PR.

**Comment by 3nids** [comment]
there seems to be more `depends_on 'XXX' => :python`

image

**Comment by kbevers** [comment]
Those are in the boneyard. I'd say you can disregard those. Maybe even just get rid of them as homebrew seem to have moved away from the concept some time ago.

**Comment by nickrobison** [comment]
I would agree with @kbevers, those are really old, unless we have any other formulae that depends on them, I would vote to remove them. If we need to add them back later, so be it.

**Comment by 3nids** [comment]
ah, right, thanks.
let's wait for Travis!

**Comment by nickrobison** [comment]
New error:

```
Homebrew setup for changed formula qca-qt@5.7...
Error: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/OSGeo/homebrew-osgeo4mac/Formula/qca-qt@5.7.rb:43:in `<class:QcaQtAT57>'
Please report this to the osgeo/osgeo4mac tap!
Or, even better, submit a PR to fix it!
```

Looking at the homebrew documentation, I can't see anything related to `:run`, I'm assuming it's used to indicate a runtime dependency, if so, seems like we can remove it?

**Comment by 3nids** [comment]
ok, removed `:run`

**Comment by 3nids** [comment]
@nickrobison I gave you access to my repo so you can push directly here (I don't have the rights to add you as committer)

**Comment by nickrobison** [comment]
@3nids Awesome! I'll do what I can to help get this resolved.

**Comment by 3nids** [comment]
I would maybe just do another round with having a list of skipped formulas for bottles.
This way the new bottles will be pushed which I think is worth a try.
I can give it a shot tomorrow.
What do you think?

In any case awesome job, thanks a lot!!!!

**Comment by nickrobison** [comment]
I do love passing builds and fresh bottles!

I think having a list of formulae which never get bottled is a good idea, but I'm concerned the scope of the PR is growing too much. Right now, anyone who has tapped this repo can't upgrade their homebrew installs because of the disabled depends_on methods, so I feel like anything we can do to get that addressed is a good thing.

Also, with 97 formulae in this change set, I'm not sure how to identify which ones build or don't. For example I know mapserver6 and qgis2 aren't building correctly, but I don't know about others, I think qt5-webkit is pointing to a missing dependency. So it might take a while to get a list narrowed down to a working subset.

But, happy to follow your lead, thanks for spending so much time on this!

**Comment by 3nids** [comment]
makes a lot of sense.
let's merge this and see what comes!
many thanks to you!

**Pull request merged**
