### PR TITLE
Add qgis3 formula

### PR DESCRIPTION
**Pull request by fjperini**
This new pull is for to have a version of https://github.com/OSGeo/homebrew-osgeo4mac/pull/403 cleaned.

I detail the few changes I made as I found errors in the previous pull.

before_install.sh: 

add tap `brewsci/bio` for `matplotlib`

.travis.yml: 

fix for python version. Requires `python3`

`sudo ln -sf /usr/local/bin/python3 /usr/local/bin/python` 

Temporary, only on travis. We have to add a fix for this in the formula.

The same for `pyrcc5`

`sudo cp ./scripts/pyrcc5.sh /usr/local/bin/pyrcc5`

### CODE REVIEW

**Comment by fjperini** [comment]
I solved it locally by adding in the formula
```
system HOMEBREW_PREFIX/"bin/pip3 install --user --upgrade wheel"
system HOMEBREW_PREFIX/"bin/pip3 install --user --upgrade setuptools"
```
It must be added in `./travis/before_install.sh`

```
${HOMEBREW_PREFIX}/bin/pip3 install --upgrade wheel
${HOMEBREW_PREFIX}/bin/pip3 install --upgrade setuptools
```

It must be applied before installing the dependencies for testing.

**Comment by fjperini** [comment]
It seems that there are no changes. Any suggestions? @nickrobison

**Comment by fjperini** [comment]
Apparently the problem is given by `pyproj`. I will try installed previously using: https://github.com/jswhit/pyproj.git
It's another solution that I found and is working locally.

**Comment by fjperini** [comment]
The problem continues. In my machine the installation was carried out without problems.

With the last changes, when constructing the package and executing the program from the Terminal, the following error appears on pop-up:

```
ModuleNotFoundError: No module named 'osgeo' 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/__init__.py", line 28, in 
    from processing.tools.dataobjects import *          # NOQA
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/tools/dataobjects.py", line 51, in 
    from processing.algs.gdal.GdalUtils import GdalUtils
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/algs/gdal/GdalUtils.py", line 38, in 
    from osgeo import ogr
  File "/usr/local/Cellar/qgis3/3.2.0/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osgeo'
```
From what I read, it has to do with `gdal2` and `gdal2-python`.

If I open the program from QGIS.app it does not report the error.

**Comment by fjperini** [comment]
It seems that the bottle `qt5-webkit-5.11.1.high_sierra.bottle.1.tar.gz` is not found:

```
==> Installing osgeo/osgeo4mac/qgis3 dependency: qt5-webkit
==> Downloading https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/qt5-webkit-5.11.1.high_sierra.bottle.1.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.9-111-g15ac935 (Macintosh; Intel Mac OS X 10.13.5) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/user/Library/Caches/Homebrew/qt5-webkit-5.11.1.high_sierra.bottle.1.tar.gz.incomplete https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/qt5-webkit-5.11.1.high_sierra.bottle.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "qt5-webkit"
Download failed: https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/qt5-webkit-5.11.1.high_sierra.bottle.1.tar.gz
```

You can check? @nickrobison

**Comment by nickrobison** [comment]
Apparently the bottles didn’t get made public, I guess I missed that step. Resolved, sorry for the holdup.

**Comment by fjperini** [comment]
The changes that I made worked. We must analyze if `qtwebkit` is fully functional, if it is we could upload this formula. @nickrobison 

When installing `pyqt5-webkit`, `qt5-webkit` was also installed (as a dependency of `qgis3` it failed, maybe if it is removed, that problem does not arise).

You have to review the `qgis3` formula to see the fixes implemented and propose ideas to solve the `pyrcc5` and `python version` (requires `python3`). All this is temporarily fixed in `before_install.sh`.

**Comment by fjperini** [comment]
I proceed to comment `qtwebkit` on the formula. Test for `qt5-webkit`, it is a dependency of `pyqt5-webkit` (it will be installed there, and the error in travis will be avoided?). If get an error,  I will choose to use `qtwebkit`, which was installed correctly.

**Comment by fjperini** [comment]
For the moment, it is better to comment `qt5-webkit` in the formula of `qgis3`. For the aforementioned error (in travis) and because after installed as a dependency of `qgis3` it causes the installation to stop.
If it is installed as a dependency of `pyqt5-webkit`, the installation of `qgis3` is completed without stopping. If all this does not work, we can use `qtwebkit` that installs correctly.

**Comment by fjperini** [comment]
Installing `qt5-webkit` as dependency of `pyqt5-webkit`, makes the installation of `qgis3` complete without stopping after installing `qt5-webkit`.

@nickrobison you could check the `qtwebkit` [formula](https://github.com/FreeCAD/homebrew-freecad/blob/master/Formula/qtwebkit.rb) (it works correctly) and this [post](https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-OS-X) to improve the `qt5-webkit`. To avoid the aforementioned drawbacks.
You have done a great job! Thank you!

**Comment by nickrobison** [comment]
@fjperini Awesome! Great work. I'll checkout on my local machine and see if I run into any other issues.

I'll also start a review of the formula and install process, we'll need to resolve all the comments before merging.

Also, I believe the issue you're observing with `qt5-webkit` is not related to the actual formula, but to the Travis install process. Currently, it's not aware of the formula dependency tree and thus can run into issues when a dependency is specified twice (either directly or implicitly) because the lock isn't released until the end of the install session. Removing the direct `qt5-webkit` dependency from the `qgis3` formula should resolve the issue. I'm hesitant to require another Tap during the installation process.

**Comment by nickrobison** [comment]
@fjperini When building on my local machine, I ran into the following error:

```
[127/4818] ccache /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_NO_CAST_TO_ASCII -DWITH_BINDINGS -DWITH_QTWEBKIT -Dqgis_native_EXPORTS -I. -I../src/native -Isrc/native -isystem /usr/local/Cellar/grass7/7.4.1/grass-base/include -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG -fPIC -fvisibility=hidden   -std=gnu++11 -MD -MT src/native/CMakeFiles/qgis_native.dir/qgsnative.cpp.o -MF src/native/CMakeFiles/qgis_native.dir/qgsnative.cpp.o.d -o src/native/CMakeFiles/qgis_native.dir/qgsnative.cpp.o -c ../src/native/qgsnative.cpp
FAILED: src/native/CMakeFiles/qgis_native.dir/qgsnative.cpp.o
ccache /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_NO_CAST_TO_ASCII -DWITH_BINDINGS -DWITH_QTWEBKIT -Dqgis_native_EXPORTS -I. -I../src/native -Isrc/native -isystem /usr/local/Cellar/grass7/7.4.1/grass-base/include -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG -fPIC -fvisibility=hidden   -std=gnu++11 -MD -MT src/native/CMakeFiles/qgis_native.dir/qgsnative.cpp.o -MF src/native/CMakeFiles/qgis_native.dir/qgsnative.cpp.o.d -o src/native/CMakeFiles/qgis_native.dir/qgsnative.cpp.o -c ../src/native/qgsnative.cpp
/bin/sh: ccache: command not found
```

Removing `ccache` resolved the issue for me. Is there a way to disable ccache in ninja in order to avoid this issue occurring on user machines?

**Comment by fjperini** [comment]
Hi @nickrobison!

Of course, at remove `qt5-webkit` from the formula does not jump that error. And it installs with `pyqt5-webkit`.

Yes, you need that ccache is not installed or linked.

I'm trying some things!

**Comment by fjperini** [comment]
I think we have to check that CMakeLists.txt is properly configured so that it does not have problems with ccache if it is installed.

```
# Configure CCache if available
IF(NOT MSVC)
  option(USE_CCACHE "Use ccache" ON)
  if (USE_CCACHE)
    find_program(CCACHE_FOUND ccache)
    if(CCACHE_FOUND)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
    endif(CCACHE_FOUND)
  endif(USE_CCACHE)
endif(NOT MSVC)

```
Some post that I was looking:
https://crascit.com/2016/04/09/using-ccache-with-cmake/
https://forum.openframeworks.cc/t/speeding-up-compilation-with-ccache-xcode-tip/23492
http://peter.eisentraut.org/blog/2014/12/01/ccache-and-clang-part-3/
https://pspdfkit.com/blog/2015/ccache-for-fun-and-profit/
https://chromium.googlesource.com/chromium/src/+/lkgr/docs/ccache_mac.md
https://gist.github.com/jjgod/4966579
https://wiki.orfeo-toolbox.org/index.php/Using_Ninja_and_ccache_to_build_OTB_faster
https://github.com/Microsoft/checkedc-clang/wiki/Faster-Builds-on-Mac-OS-X---Linux-with-CCache
https://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake
http://www.brianlheim.com/2017/08/20/supercollider-travisci.html

**Comment by 3nids** [comment]
Temporarly you can disable building with ccache with `-DUSE_CCACHE=OFF`

Could it be that ccacke is not linked and hence not found?

**Comment by nickrobison** [comment]
I believe my ccache installation was correct, I installed by default from Homebrew and updated my PATH correctly, but it’s possible something went wrong.

We can leave it as it, if other folks aren’t seeing the issue. I know Luis reported the same error.

**Comment by fjperini** [comment]
Well, now it is only necessary to review the formula and see the changes I made to solve the problems they presented.

**Comment by ruaridhw** [comment]
@nickrobison, for what it's worth, I followed through #396 and ran into the same error as @luisspuerto though I don't believe I have `ccache` installed...

```
brew install https://raw.githubusercontent.com/fjperini/homebrew-osgeo4mac/qgis3/Formula/qgis3.rb

ninja: build stopped: subcommand failed.

==> Formula
Path: /Users/ruaridhw/Library/Caches/Homebrew/Formula/qgis3.rb
==> Configuration
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8375456c7bf98c3e98db93dda99a7d447a193ecc
Core tap last commit: 49 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1
macOS: 10.13.4-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/bison:/usr/local/opt/flex:/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/qt:/usr/local/opt/qt5-webkit:/usr/local/opt/expat:/usr/local/opt/libxml2:/usr/local/opt/gdal2:/usr/local/opt/gdal2-python:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
```

**Comment by christianbraun** [comment]
I also changed my files according to this pull request and it doesn't compile (ninja error).

**Comment by nickrobison** [comment]
@ruaridhw @christianbraun Sorry to hear that you're having trouble. Unfortunately, the `ninja: build stopped: subcommand failed` is a fairly generic error that basically means 'didn't compile'.

Would you be able to upload more information by running:

`brew gist-logs qgis2`? And then post the link?

You may also need to follow the instructions [here](
https://github.com/OSGeo/homebrew-osgeo4mac/wiki/Finding-a-parallel-job-compilation-error), in order to really pinpoint the error.

Once you do that, I'm sure either myself or @fjperini can help sort it out.

**Comment by christianbraun** [comment]
Hi, here are my gist logs for qgis2 and qgis3
https://gist.github.com/christianbraun

**Comment by fjperini** [comment]
@christianbraun @nickrobison I review it. 
Working on the formula, more orderly and detailed.

**Comment by fjperini** [comment]
@christianbraun `pyqt` is installed, but it seems you have the following problem:

```
Traceback (most recent call last):
  File "/tmp/qgis3-20180725-91033-kovxgv/cmake/FindPyQt5.py", line 37, in <module>
    import PyQt5.QtCore
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```
Try again after adding in your `~/.bashrc`:

```
export PYTHONPATH=/usr/local/lib/python3.7/site-packages:$PYTHONPATH
```

**Comment by ruaridhw** [comment]
Gist logs uploaded [here](https://gist.github.com/ruaridhw/50f8135e3987352346c801e264baeeac).

This seems to be the [output error](https://gist.github.com/ruaridhw/50f8135e3987352346c801e264baeeac#file-05-cmake-L83-L85) but I can't say I know why it would be reporting a version "1.4" of `PythonInterp`...

**Comment by fjperini** [comment]
@rouault you are having this error:

```
CMake Error at /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
is at least "3" (found /usr/local/bin/python3)
```
Verify that

```
python --version
Python 3.7.0
```

A quick solution:

```
echo 'alias python="/usr/local/bin/python3"' >> ~/.bash_profile`
```
and set `PYTHONPATH`.

To have a reference

```
PythonInterp: /usr/local/bin/python3 (found suitable version "3.7", minimum required is "3") 
Python executable: /usr/local/bin/python3
Python version: 3.7.0
Python library: /usr/local/Frameworks/Python.framework/Versions/3.7/Python
Python site-packages: /usr/local/lib/python3.7/site-packages
PyQt5 version: 5.10.1
```

@christianbraun modify the file `/usr/local/bin/pyrcc5` and change `pythonw2.7` to `python3`.

**Comment by rouault** [comment]
> @rouault you are having this error:

@fjperini Not sure why you ping me on this...

**Comment by ruaridhw** [comment]
@fjperini, thanks for your help with this. Here are the [latest logs](https://gist.github.com/149937ee74e528e87ef6679bb5b3beda).

**Comment by fjperini** [comment]
@rouault I'm sorry, it was a message to @ruaridhw

**Comment by fjperini** [comment]
@ruaridhw you must modify the file `/usr/local/bin/pyrcc5`.

**Comment by nickrobison** [comment]
@fjperini Just a heads up, these python issues will need to be dealt with in the Formula itself, modifying files in other directories is not going to be a long-term solution. You might want to take a look at some of the recent changes I made to the `qgis2` formula, and the way it handles the python dependencies.

If we can't get QGIS building and installing without having to manually modify files, then we'll need to hold off on merging this.

**Comment by fjperini** [comment]
@nickrobison Yes, I was reviewing the changes you made in `qgis2`. I will incorporate the necessary changes to avoid the inconveniences that are having.

**Comment by ruaridhw** [comment]
@fjperini brilliant, it works now. Thanks very much for your perseverance!

**Comment by luisspuerto** [comment]
I got this errors ([gist](https://gist.github.com/luisspuerto/bc9445b8f686caa4a8dc471587678f9b)) yesterday when trying to update to QGIS3 3.2.1. 

One is with the devs formula —the second one— and the first one is with @fjperini formula. 

by the way I needed to modify the Orfeo formula to correct the dependency to: 

```sh
Error: No available formula with the name "brewsci/science/opencv" (dependency of qgis/qgisdev/qgis3-dev)
```

I can modify all the formulae where have a dependency of `brewsci/science/opencv` and change just for `opencv` and make a pull request.

**Comment by luisspuerto** [comment]
PS/ I just update the [gist](url
https://gist.github.com/luisspuerto/bc9445b8f686caa4a8dc471587678f9b) with a third error log. In my previous attempt i didn't change the `/usr/local/bin/pyrcc5` file... but I still get an error.

**Comment by christianbraun** [comment]
@fjperini working for me as well. thanks a lot for your contributions and patience!

**Comment by luisspuerto** [comment]
@fjperini does that mean that we should revert changes on `/usr/local/bin/pyrcc5`

**Comment by fjperini** [comment]
@luisspuerto No, I used `gsed` to apply the change in `pyrcc5`, so it will only be modified if `pythonw2.7` is present.

**Comment by luisspuerto** [comment]
by the way, update to version 3.2.1 please.

**Comment by fjperini** [comment]
Do not take into the build above, I just corrected the conflict problem I had previously.

**Pull request closed without merging**
