### PR TITLE
QGIS v3.2.0

### PR DESCRIPTION
**Pull request by fjperini**
The formula works correctly for `gis/homebrew-qgisdev`. Was added  `brewsci/bio` for fix`matplotlib`. For more details, see this [issue](https://github.com/OSGeo/homebrew-osgeo4mac/issues/396).

### CODE REVIEW

**Comment by nickrobison** [comment]
Thanks for this! A few comments on the formula.

Also, what are the new files introduced in the `scripts` directory for?

One point of discussion, qt-webkit is deprecated and no longer shipped with QT5. Unless there's a compelling reason to keep it, I would suggest disabling it in the build. Otherwise we'll probably end up having to support our own Q5 version. Which I'd like to avoid.

@3nids @luisspuerto and @kbevers might have some thoughts on whether or not we can remove webkit support.

**Comment by kbevers** [comment]
> @3nids @luisspuerto and @kbevers might have some thoughts on whether or not we can remove webkit support.

I don't know anything about it. But if it is not a part of QT5 I think it should be removed. It's going to be a pain to maintain a separate qt formula!

**Comment by luisspuerto** [comment]
> @3nids @luisspuerto and @kbevers might have some thoughts on whether or not we can remove webkit support.

@nickrobison in the same way as @kbevers don't really know anything about this... My two cents here is formulae should provide the same capabilities as the version download from the web and options should be an extra that make formulae more attractive. 

If I'm not going the same thing (or better) I can get from the official download why bother to build/install?

**Comment by fjperini** [comment]
I just see your comments. I was just testing some things to see possible problems. 

If `qt5-webkit` is not necessary, it is best to remove it. I needed to install it with  `--non-sandbox`.

At the end of the installation of `gdal2-python` did not continue with the other dependencies, so I made some changes to continue.

It stops when you begin to compile in [(TRAVIS CI)](https://travis-ci.com/OSGeo/homebrew-osgeo4mac/builds/77304632?utm_source=github_status&utm_medium=notification) the package

```
Installing changed formula qgis3...
==> Installing qgis3 from osgeo/osgeo4mac
==> Cloning https://github.com/qgis/QGIS.git
Cloning into '/Users/travis/Library/Caches/Homebrew/qgis3--git'...
remote: Counting objects: 15427, done.
remote: Compressing objects: 100% (11683/11683), done.
remote: Total 15427 (delta 5055), reused 8807 (delta 3579), pack-reused 0
Receiving objects: 100% (15427/15427), 98.72 MiB | 21.52 MiB/s, done.
Resolving deltas: 100% (5055/5055), done.
Checking out files: 100% (14463/14463), done.
==> Checking out branch release-3_2
==> /usr/local/bin/pip3 install --user future psycopg2 python-dateutil httplib2 
==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-D
==> cmake --build . --target all -- -j 2
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Later I will continue working on this.

@nickrobison @kbevers @luisspuerto 

Thanks!

**Comment by dmey** [comment]
There is an issue with using `QtWebEngineWidgets`, the replacement for `QtWebKit` in QGIS see 
 [this issue](https://issues.qgis.org/issues/18155). @nyalldawson do you have any thoughts?

**Comment by nickrobison** [comment]
@fjperini Can you please squash down your changes to only a couple of commits? It's a bit difficult to see what's actually going on. Also, can you please explain your changes to the build process? Since it's been working fine for the last couple of months, I'm hesitant to pull any other changes.

@luisspuerto Your thoughts largely echo mine, but I think we might need to make an exception for the WebKit support. I'm just trying to figure out what it's used for and what might potentially break if we remove it.

**Comment by nickrobison** [comment]
@fjperini The build error you're seeing appears to be because ninja doesn't output anything to the console while it's building. That's why we added the various

```bash
while true; do
    sleep 30
    if jobs -rp | grep ${PID} >/dev/null; then
      echo "."
    else
      echo
      break
    fi
  done
```

blocks to the build script.

**Comment by dmey** [comment]
>  I think in this case, we might need to make an exception for the WebKit support.

@nickrobison Ceasing support for `WebKit` would make sense but there are plugins who rely on `WebKit` and cannot switch to `QtWebEngineWidgets` because of [this issue](https://issues.qgis.org/issues/18155). Don't you think that this should be fixed first? We may end up with a number of unsupported plugins if the user chooses to install QGIS via Homebrew...

**Comment by luisspuerto** [comment]
@nickrobison isn't there already a [formula for QT5 in homebrew-osgeo4mac](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/qt5-webkit.rb)?

**Comment by nickrobison** [comment]
@dmey I definitely don't want to break any existing plugins. We may have to hold off on merging this until that ticket is addressed. Looks like there's not a timeline for doing so, correct?

The other option is to simply make clear when installing that WebKit plugins are temporarily not supported. But I don't know how widespread the issue is, is there a way to search for webkit plugins?

@luisspuerto That formula expects QT 5.9, where as the Homebrew QT formula is 5.11. I'm not sure what might break when trying to mix the two.

**Comment by fjperini** [comment]
I changed it previously because I was loading the `qt5-webkit` package already installed.

```
==> Installing qgis3 from osgeo / osgeo4mac
qt5-webkit: Must be built with `brew install --no-sandbox ...`, or install steps will fail.
Error: An unsatisfied requirement failed this build.
```

It has something to do with following files

install.sh:

```
  echo "Installing dependencies for changed formulated $ {f} ..."
  brew install --only-dependencies --build-bottle $ {TRAVIS_REPO_SLUG} / $ {f} &
```
script.sh:

```
  echo "Installing changed formula $ {f} ..."
  brew install --build-bottle $ {TRAVIS_REPO_SLUG} / $ {f} &
```

if I just using

install.sh:

```
  echo "Installing dependencies for changed formulated $ {f} ..."
  brew install $ {f} --only-dependencies
```


script.sh:

```
  echo "Installing changed formula $ {f} ..."
  brew install $ {f}
```

Skipped the mentioned error, but the compilation of the package stops.

We must review what happens with `qt5-webkit` and `qdal2-python`, they make the installation stop. That's why I made some changes in travis.yml to install them from there, and continue with the construction of `qgis3`.

Other things I did there:

- A link to have `python3` as `python`
- Fix to `pyrcc5`
- Before installing `gdal2-python`, it is required
 `brew install numpy || brew link --overwrite numpy`

You can check all this!

**Comment by nickrobison** [comment]
@fjperini The two commands you modified (in install.sh and script.sh) are not the same. We need the `--build-bottle` command in order to get the packaging to work correctly. I understand what you did, I'm just not sure why and the commits simply say `Test:` which isn't very clear.

I think the first step is to remove the qt5-webkit dependency and temporarily revert the build changes (which we'll need to do anyways because we don't want to install gdal on each CI run) to see what in the formula itself is actually failing. My suspicion is that we'll need to make a tweak or two to the build process, but when doing so we'll need to consider how it might affect other formulae.

You can see in the commit history that we spent a lot of time working on the CI setup the other month, so it's a tricky process.

Does that make sense? I really appreciate how hard you're working to make this happen!

**Comment by fjperini** [comment]
Clear! @nickrobison It was to avoid the problem with `qt5-webkit`. I regret not having detailed everything before. There were only a few changes to be sure of what happened in Travis CI, and skip some inconevnientes and see how the installation continued to visualize some other error,

I agree. I hope we can remove `qt5-webkit`, and reconfigure everything to avoid problems that arise.

I imagine it has its difficulty, but making those changes will ensure a simple installation of `qgis3`.

I appreciate your answers!

**Comment by nyalldawson** [comment]
I'd caution against dropping the WebKit dependency. There's parts of core qgis which depend on this (e.g. layout html items won't work without it), and many 3rd party plugins still rely on it being present (e.g. Inasafe).

Webengine just isn't a viable alternative. We tried to port to it in 3.0, but it's functionality is very limited and doesn't meet qgis' needs. So a port isn't on the cards, and the WebKit dependency will remain throughout the whole 3.x series.

**Comment by nickrobison** [comment]
@nyalldawson That's great feedback, thanks for the information! Do you know which version of QT is currently being built against? It sounds like we'll need to figure out how to get QT 5.9 building via one of our own formulas in order to have webkit support.

**Comment by nyalldawson** [comment]
Anything from 5.5 up should work, but bugs in 5.6 make the experience far from ideal. I'd suggest 5.7 as a minimum, 5.9 and up recommended.

**Comment by nickrobison** [comment]
Are there still webkit modules for the latest versions, such as 5.11? Or is it possible to build qt-webkit 5.9 against QT 5.11?

**Comment by nyalldawson** [comment]
I can't comment on the homebrew status, but Qt upstream reversed the decision to deprecate webkit and there's builds of it for all recent versions.

**Comment by fjperini** [comment]
Good clarification! @nyalldawson @nickrobison 

I was reviewing the packages for Macport and ArchLinux.
We could review these configurations, maybe contribute something.
In ArchLinux, `v5.212.0-alpha2` was used to create `qt5-webkit`.
Macport uses `v5.10.1` (It can be used `v5.11.1`?).

In GNU Linux everything is a little simpler! :satisfied:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qt5-webkit-git
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-webkit
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qgis-git
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/qgis
https://github.com/macports/macports-ports/blob/master/gis/qgis3/Portfile
https://github.com/macports/macports-ports/blob/master/aqua/qt5/Portfile

It's just an idea, this may not help much.

**Comment by 3nids** [comment]
sorry for popping late in the discussion.

First many thanks to @fjperini for bringing this!!!!

As Nyall pointed, QtWebkit is back into Qt source since 5.9.
Anyway, QGIS 3 will be built against at least 5.9.

So we should easily be able to remove our own formulas (qt5-webkit.rb, pyqt5-webkit.rb but keep the 5.7 for QGIS 2), but this could/should be done separately from this PR.

@fjperini are you able to change the formula to rely on the native webkit?

**Comment by nickrobison** [comment]
@3nids @nyalldawson Good to hear about webkit still being supported! It looks like the ubuntu and arch packages are building from the tip of [this repo](https://github.com/qt/qtwebkit) which to be slightly trailing the webkit master, but should get us close at least. I can work on updating that formula, I believe that if I can get the bottle to build, it won't require building in the sandbox, which would simplify things.

**Comment by fjperini** [comment]
Great! I think you can achieve it! @nickrobison 

the above was just one last test :pray:

I reversed the changes in install.sh and in script.sh, I had even complied qgis3, but reversing these files I return to the inconvenience with `qt5-webkit`.

Then you have to see the `gdal2-python`, after being installed makes the installation of `qgis3` stop. 
That's why I install it before.

And find a solution for `pyrcc5`

Let's go step by step! :muscle:

**Comment by fjperini** [comment]
Great @nickrobison , I see that you're already in it. I wait for those changes to try again.

**Comment by nickrobison** [comment]
@fjperini We might want to hold off on making any changes until I can get #404 merged in, along with an update to `pyqt5-webkit` which is also causing issues.

Once that gets merged, I'll need you to rebase against master. I made some changes to the build process to handle installing webkit in the sandbox. Plus, we'll need to latest bottle, otherwise the Travis job will never complete.

**Comment by fjperini** [comment]
Sure, I understand. :+1:

**Comment by nickrobison** [comment]
@fjperini `qt5-webkit` and `pyqt5-webkit` have been rebuilt and updated to the latest versions. Can you rebase against master and try your build again?

**Comment by fjperini** [comment]
Yes @nickrobison, I think we'll have to do a new pull to make it cleaner(if required). It seems to you to rename the formula to only `qgis`?

Let's try to see how it turns out.

**Comment by nickrobison** [comment]
Are you asking if I renamed the formula, or if we should rename to to simply, qgis?

I think we should keep the `qgis3` name for now, because that's consistent with what we name things in this tap. I've been thinking about moving to the `@3` suffix like they do in core, but we'll see.

I think a new PR is a great idea, I'm also about to push a commit that should remove the need to build with the `--no-sandbox` flag, so I'll let you know when that's ready.

**Comment by nickrobison** [comment]
Looks like we'll need to hold off until the bottle rebuild is done. Should only be a few more minutes, then I'll restart the build. I just pushed a bunch of updates to GDAL.

**Comment by fjperini** [comment]
Yes @nickrobison , we leave it like that. I await your news.

**Comment by fjperini** [comment]
@nickrobison For some reason I am having this error:

```
0.02s$ ./travis/install.sh
./travis/install.sh: line 22: syntax error near unexpected token `<<<'
```

It's a syntax problem, but I do not visualize it. You can see it?

**Comment by nickrobison** [comment]
With the commit history, it's really hard to see what's going on and where the various changes are coming from. Can you please squash down to a commit or two and rebase against master?

If you need to create a new PR to make it easier, that would work too. Thanks!

**Comment by fjperini** [comment]
Yes I agree! Better to open a new PR.

**Pull request closed without merging**
