### PR TITLE
Qgis 2.14

### PR DESCRIPTION
**Pull request by m-kuhn**
Includes a formula for QGIS 2.14 ~~and also updates gdal to 2.0.2~~

### CODE REVIEW

**Comment by m-kuhn** [comment]
Removed GDAL in favour of #122

**Comment by oeon** [comment]
```
CMake Error at cmake/FindQCA.cmake:64 (message):
  Could not find QCA
Call Stack (most recent call first):
  CMakeLists.txt:312 (FIND_PACKAGE)
```

`brew install qca` allowed me to install.

Thanks for adding this!

**Comment by m-kuhn** [comment]
@oeon thanks for pointing out, I hope the latest commit fixes this

**Comment by m-kuhn** [comment]
@dakcarto what do you think, can this be merged?

**Comment by dakcarto** [comment]
Hi. I can review this over the weekend. Thanks for the contribution!

**Comment by m-kuhn** [comment]
Thanks. It would be great to bundle this with #122

**Comment by dakcarto** [comment]
Hi. This has been merged via cherry-pick and now defaults to GDAL/OGR v2.x and GRASS7.

Thanks!

**Pull request closed without merging**
