### PR TITLE
Add Formula for QGIS 2.16

### PR DESCRIPTION
**Pull request by m-kuhn**
Trivial patch. More or less equal to

    cp qgis-214.rb qgis-216.rb
    sed -i 's/214/216/g' qgis-216.rb

### CODE REVIEW

**Comment by dakcarto** [comment]
Note: I will be abandoning the version in the `qgis-xxx` formulae and instituting a `qgis` release (with `master_2` branch for --HEAD option), `qgis-ltr` LTR (with `release-2_14` for --HEAD option) and `qgis-dev` HEAD-only formulae, in preparation for moving to Homebrew repos (though having more than one formula may be frowned upon — even if it is necessary though for at least 6-10 months).

**Comment by m-kuhn** [comment]
Sounds good to me. The `release-2_16` branch will be missing, but yes, I agree that `master_2` is more important than that.

All of them can be built with different qt/python versions individually? default to qt4/py2 for the qgis2 branches, qt5/py3 for the qgis3 branch?

**Comment by dakcarto** [comment]
> All of them can be built with different qt/python versions individually? default to qt4/py2 for the qgis2 branches, qt5/py3 for the qgis3 branch?

I'm setting up a pull request for Homebrew that supports those options in upstream formulae (`qscintilla2`, `qwt`, `qca`, etc.). Also, still working on custom formulae that will allow all of them to be installed locally at the same time.

**Comment by m-kuhn** [comment]
@dakcarto gentle ping, any news on this?

**Comment by jctull** [comment]
@dakcarto The recent repo work is appreciated. Anything to add on the status of your plans for qgis2? Did the pull request for upstream formulae go through?

My recent flirting with macports has not converted me from homebrew, but homebrew seems to be falling short for osgeo needs on the Mac.

**Comment by dakcarto** [comment]
@m-kuhn and @jctull  sorry for the delay. There are now `qgis2` and `qgis2-ltr` formulae.

These `qgsi2*` formulae are based upon keg-only builds of the new `qt-4`-related formulae (see https://github.com/OSGeo/homebrew-osgeo4mac/issues/177#issuecomment-253993786), since Qt4 is actively being _removed_, not just deprecated, in Homebrew-core. This sets the groundwork for `qgis3*` formulae to be built upon Qt5/PyQt5/Py3 while still having `qgis2*` formulae installed.

`qgis2-dev` and `qgis3-dev` formulae are in the works for https://github.com/qgis/homebrew-qgisdev, but some Homebrew-core formulae that need Qt5 options are just now being finished (e.g. https://github.com/Homebrew/homebrew-core/pull/5949 and  https://github.com/Homebrew/homebrew-core/pull/5162).

See also ongoing move-to-Qt5 effort: https://github.com/Homebrew/homebrew-core/issues/1705

**Comment by m-kuhn** [comment]
Thanks for the update @dakcarto .
Much appreciated :+1:
I'm very (very) much looking forward to the Qt5 based formula.

**Comment by jctull** [comment]
Ditto. I’m glad to see your activity again, Larry. We are pretty much at a loss without you in my opinion.

I’m currently working back to a functional setup working directly from your repo on Sierra. Hopefully all goes well.

**Pull request closed without merging**
