### PR TITLE
update proj to 6.1

### PR DESCRIPTION
**Pull request by 3nids**
we should be good to go now if I'm right
ping @PeterPetrik

### CODE REVIEW

**Comment by PeterPetrik** [comment]
I would be more conservative and wait for @nyalldawson confirmation

**Comment by fjperini** [comment]
@3nids @PeterPetrik I see, we could start using proj6 and gdal3. But to be sure, let's wait for the confirmation @nyalldawson

**Comment by 3nids** [comment]
let's see if gdal builds fine

**Comment by fjperini** [comment]
@3nids it builds correctly, but it fails in testing because you must first update other dependencies that depend on PROJ.

@PeterPetrik @nyalldawson If there is agreement, we can start with these updates.

**Comment by nyalldawson** [comment]
My 2c is that I'd ultimately aim for an upgrade at around early August/late July. That gives a month to identify any major issues with proj 6/gdal 3 themselves, and how QGIS uses them.

I'm a HUGE fan of proj 6, and would love to see QGIS move to this ASAP, but at the same time there's been a ton of code churn and projection handling is critical GIS functionality :laughing: 

So I'd say getting the pieces in place now is a good idea, but I'd hold off on hitting the switch for another month.

**Comment by 3nids** [comment]
@nyalldawson thanks for the feedback.

**Comment by fjperini** [comment]
@nyalldawson we can already use PROJ 6 and GDAL 3?

**Comment by nyalldawson** [comment]
Yes - I think it's a suitable time to upgrade now

**Pull request closed without merging**
