### PR TITLE
qt5-webkit: ninja used for speed

### PR DESCRIPTION
**Pull request by fjperini**
@nickrobison This should reduce the build time and be below the limit in TravisCI.

### CODE REVIEW

**Comment by fjperini** [comment]
It was very close to completion:

https://travis-ci.com/OSGeo/homebrew-osgeo4mac/builds/94013465

```
==> make install
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall osgeo/osgeo4mac/qt5-webkit`
==> Caveats
qt5-webkit is keg-only, which means it was not symlinked into /usr/local,
because because Qt5 is keg-only.
For compilers to find qt5-webkit you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt5-webkit/lib"
  export CPPFLAGS="-I/usr/local/opt/qt5-webkit/include"
For pkg-config to find qt5-webkit you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt5-webkit/lib/pkgconfig"
==> Summary
🍺  /usr/local/Cellar/qt5-webkit/5.12.0: 166 files, 44.8MB, built in 110 minutes 34 seconds
Testing changed formula qt5-webkit...
Testing osgeo/osgeo4mac/qt5-webkit
The job exceeded the maximum time limit for jobs, and has been terminated.
```

https://travis-ci.com/OSGeo/homebrew-osgeo4mac/builds/94518154

```
==> cmake --build . --target install -- -j 2
Error: An exception occurred within a child process:
  MachO::DylibUnknownError: No such dylib name: @rpath/QtWebKit.framework/Versions/5/QtWebKit
```

I will use the current version to check some things.

**Comment by nickrobison** [comment]
@fjperini I don't really think Ninja is going to help here, my understanding is that it improves the build/debug cycle by reducing the amount of work required to determine changed files to recompile. For a single build, you probably won't see much improvement.

Also, does't Homebrew automatically use all available cores, unless you specify `ENV.deparallelize`?

**Comment by fjperini** [comment]
@nickrobison I understand you.

I was just doing some tests, since the build should not exceed the time limit.

Maybe this will be solved with CircleCI

**Comment by nickrobison** [comment]
@fjperini I should be! Circle CI jobs time out after 5 hours, and some quick tests showed `qt5-webkit` building in less than an hour. So that should be great!

**Comment by nickrobison** [comment]
Is there an issue with building qt5-webkit on Mojave? If so, if you open a PR, and I merge and rebuild manually tomorrow night.

**Comment by fjperini** [comment]
No problem in Mojave. I was just doing some tests.

Anyway I think that this formula
https://github.com/fjperini/homebrew-osgeo4mac/blob/3051c11ccdec2e0f42cd3c55a411c33f8f225cad/Formula/qt5-webkit.rb
 is better.

**Comment by fjperini** [comment]
@nickrobison when Circle CI is already available, let's try with this new formula for `qt5-webkit`.

**Pull request closed without merging**
