### PR TITLE
Update osgeo-grass.rb

### PR DESCRIPTION
**Pull request by PeterPetrik**
use osgeo-pyqt

### CODE REVIEW

**Comment by fjperini** [comment]
Hi @PeterPetrik!
In the transxuero of the day I will finish the process of revision of all the formulas. We are renaming and updating.

Sorry for the inconveniences.

**Comment by PeterPetrik** [comment]
its quite difficult for qgis-mac-packager to keep up to date with all of this shuffling, but hopefully the bulk of renaming is done?

**Comment by fjperini** [comment]
yes, there are only a few formulas left. It's ready in a couple of hours!

**Comment by fjperini** [comment]
for qgis-mac-packager it would only be necessary to update `osgeo-grass` and rebuild` osgeo-qt-psql`, `osgeo-qt-odbc`, `osgeo-qt-mysql` and `osgeo-saga-lts`. Qt was recently updated.

With that you can continue your work.

The other formulas that are missing rename and revise are secondary.

I'm updating `osgeo-sip`, and `osgeo-pyqt` and `osgeo-pyqt-webkit`. New versions recently published.

**Comment by fjperini** [comment]
I will update this in another pull, to apply other changes.

You can join to be in more contact:

https://join.slack.com/t/homebrew-osgeo4mac/shared_invite/enQtNTY2NjcxOTg4Nzg5LTJjZGIxMGY0MWU5OGEyOTJhYzViNzJiYzJlZGEwZTRiMDc4MzkyY2IzZTA2MDljNDlhM2M5ZGE2OWM0MGQ3Y2I

**Comment by fjperini** [comment]
Updated to 7.6.1, building the bottles...

**Pull request closed without merging**
