### PR TITLE
qt5-webkit depends on webp fix

### PR DESCRIPTION
**Pull request by fjperini**
Error executing the program `qgis3`
```
dyld: Library not loaded: /usr/local/opt/webp/lib/libwebp.7.dylib
  Referenced from: /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Versions/5/QtWebKit
  Reason: image not found
```

### CODE REVIEW

**Comment by nickrobison** [comment]
That error isn’t very descriptive? Where did you encounter it?

WebP should be optional with WebKit did you confirm this resolves your issue?

**Comment by fjperini** [comment]
When I run the program `qgis3` failed, In the terminal was that message.
When I installed webp I could open it without problems.

**Comment by nickrobison** [comment]
Ok. I see what's going on. Good catch!

Webp is an optional dependency, but CMake dragged in the library when I built on my local machine. The Sierra VM I used it didn't have webp installed, so no symbol issues.

Since webp is an optional dependency we should probably keep it that way, but we'll need to modify the CMake script in order to keep it from going awry. I can handle that in a bit, unless you want to make the changes.

**Comment by fjperini** [comment]
I leave it to you! :+1:
As it was not a big mistake, I did a pull. It is better to open a issue for these things. :grimacing: Ha!

**Comment by nickrobison** [comment]
@fjperini This should be resolved in #412. Unless I missed another dependency! If we run into any other issues, we can just duplicate the Sierra bottle, like we do for everything else.

I also just added `webp` as a dependency, because the cmake config is generated by qmake, and I couldn't figure out a clean way of adding the optional dependency without doing a manual patch. So your original fix was the one that made it!

Let me know if you run into any other issues.

**Pull request closed without merging**
