### PR TITLE
Switch license to two-clause BSD (same as Homebrew's) from GPL2

### PR DESCRIPTION
**Pull request by dakcarto**
Hi @jctull, @nickrobison, @hobu, @rkrug, @cspanring, @m-kuhn, @fphilipe, @zitterbewegung,

In preparation for moving formulae to [homebrew/homebrew-geospatial](https://github.com/orgs/Homebrew/teams/geospatial), I'd like to switch the license from GPL2 to BSD (same as Homebrew's). Having these formulae in an official repo of the Homebrew project means they will be auto-built to bottles, etc. and have a larger pool of contributors.

You have contributed to this repo and I would like to hear any opinions on whether you agree or disagree to switching the license.

### CODE REVIEW

**Comment by hobu** [comment]
:thumbsup:

**Comment by m-kuhn** [comment]
No objections 👍

**Comment by fphilipe** [comment]
👍

**Comment by nickrobison** [comment]
Sounds good to me.

**Comment by jctull** [comment]
No problems here. Once this all gets back in order, I will probably abandon my fork in favor of contributing to the homebrew-geospatial repo as possible.

**Comment by dakcarto** [comment]
Hi @rkrug, @cspanring, @zitterbewegung,

Any opinions on whether you agree or disagree to switching the license?

**Comment by rkrug** [comment]
Fine with me.

Rainer

Le dimanche 24 avril 2016, Larry Shaffer <notifications@github.com> a
écrit :

> Hi @rkrug <https://github.com/rkrug>, @cspanring
> <https://github.com/cspanring>, @zitterbewegung
> <https://github.com/zitterbewegung>,
>
> Any opinions on whether you agree or disagree to switching the license?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OSGeo/homebrew-osgeo4mac/pull/131#issuecomment-213852338>
>


-- 
Rainer M. Krug, PhD (Conservation Ecology, SUN), MSc (Conservation Biology,
UCT), Dipl. Phys. (Germany)

Centre of Excellence for Invasion Biology
Stellenbosch University
South Africa

Tel :       +33 - (0)9 53 10 27 44
Cell:       +33 - (0)6 85 62 59 98
Fax (F):       +33 - (0)9 58 10 27 44

Fax (D):    +49 - (0)3 21 21 25 22 44

email:      Rainer@krugs.de

Skype:      RMkrug

**Comment by dakcarto** [comment]
Hi @cspanring, @zitterbewegung,

Any opinions on whether you agree or disagree to switching the license?

**Comment by zitterbewegung** [comment]
I agree with switching the license .

**Comment by dakcarto** [comment]
Hi @cspanring,

Any opinions on whether you agree or disagree to switching the license?

**Pull request merged**
