### PR TITLE
grass7: other corrections

### PR DESCRIPTION
**Pull request by fjperini**
Solution for the problem reported in #452.
Dependencies, configurations and corrections are added.

### CODE REVIEW

**Comment by nickrobison** [comment]
@fjperini Please see my comment on #550.

Please specify what corrections were actually made (what each change solved) and why the new dependencies are added. I really don't want to make R a hard dependency for installation, can it be optional instead?

**Comment by nickrobison** [comment]
@fjperini I understand that adding the dependencies increases support for various operations, what I don't understand is why all of them need to be enabled by default (without the option to disable them) for bottle builds. For example, why are we pulling in OpenGL libraries for command line only installs? Or, liblas when we have an option for liblas via gdal?

I'm really concerned that this is going to dramatically increase install size and complexity, for features that not every user needs. Thoughts?

**Comment by fjperini** [comment]
@nickrobison Yes, several can be set as optional.

> Why are we incorporating OpenGL libraries to install only on the command line? 

I think so, what do you say?

**Comment by nickrobison** [comment]
@fjperini I would say that most (if not all) of these dependencies should be made optional. Unless you feel like some are used by the majority of GRASS users.

**Comment by fjperini** [comment]
@nickrobison Well, let's leave all the added as optional.

**Comment by fjperini** [comment]
@nickrobison Ready! All aggregate dependencies were set as optional.

**Pull request merged**
