### PR TITLE
Update to webkit 5.7.1

### PR DESCRIPTION
**Pull request by m-kuhn**
* and fixes a deprecation warning
* and adds a bottle

### CODE REVIEW

**Comment by dakcarto** [comment]
@m-kuhn thanks for the update on this. Currently, Travis CI here is building against macOS Sierra 10.12 and automates bottling (though QtWebKit times out, of course!).

Can you bottle for Sierra as well? If not, I'll need to do so in a VM, which creates a conundrum: macOS-versioned bottles can't have different origins. All bottles must come from same origin. In which case, I could download your binary and upload it under http://qgis.dakotacarto.com/bottles with the other, newer bottles. I don't see any issues with that approach.

**Comment by m-kuhn** [comment]
@dakcarto I only have this el cap system here, but I think travis is based on them (see e.g. https://travis-ci.org/m-kuhn/QGIS/builds/189992185#L700).

We could also use osgeo/homebre-osgeo4mac releases as download centre for the latest bottles, so everyone (with proper access rights) could upload the builds there, potentially even directly upload them from a after_success script in travis?

**Comment by dakcarto** [comment]
@m-kuhn, the Travis setup for this repo already auto-uploads the bottles to my S3 bucket. It's just the time out issue again, so I have to build those large items on local Vagrant-based VMs. While the move to `Homebrew-geospatial` would help in this area, I think many of the formulae might be rejected because they don't match Homebrew style of doing things.

If I have time, I might set up Jenkins to do bottling jobs on my older build server (used to use for Mac nightlies).

**Comment by m-kuhn** [comment]
I just realized that my build is looking for `/usr/local/Cellar/qt5/5.7.1_1/lib/QtWebKit.framework` which it cannot find.

What I did is build the bottle on this machine (then `brew cleanup qt5-webkit` after the error appeared I also did `brew reinstall qt5-webkit` from the bottle).

Finally I worked around the issue with

    ln -s /usr/local/opt/qt5-webkit/Frameworks/QtWebKit.framework /usr/local/Cellar/qt5/5.7.1_1/lib/QtWebKit.framework

Any idea what could have gone wrong?

**Comment by dakcarto** [comment]
@m-kuhn wrote:
> I just realized that my build is looking for /usr/local/Cellar/qt5/5.7.1_1/lib/QtWebKit.framework which it cannot find.

You mean your own custom QGIS build, or `qgis3-dev` build?

**Comment by m-kuhn** [comment]
`qgis3-dev` IIRC (or both?) but if no one else complains it probably was a local issue

**Pull request closed without merging**
