### PR TITLE
Correcting my name in the formula

### PR DESCRIPTION
**Pull request by luispuerto**
@fjperini THANKS A LOT FOR PUT MY NAME HERE!! 🙇 🙏 

I almost did nothing! @fjperini you did all the work. GREAT WORK! we owe you a couple of beers🍻 !!!

### CODE REVIEW

**Comment by fjperini** [comment]
@luispuerto It's like tasting several beers!

I had put your twitter!

We will merge this, and since we are updating a more recent commit.

**Comment by luispuerto** [comment]
>I had put your twitter!

But yours and @nickrobison is the twitter or the GitHub account. Either for me is fine, I was just guessing that it has to make reference to github accounts.

**Comment by luispuerto** [comment]
If the yours and @nickrobison's are also the twitter account, leave like that and close the pull request.

**Comment by fjperini** [comment]
matches our twitter account. ha!

I agree, it is better that you refer to the GitHub account

**Pull request merged**
